[package]
name = "spenceros"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "./bootloader/common/" }
badfs = { git = "https://github.com/spencer3035/badfs", branch = "main" }
# ovmf-prebuilt = "0.2.7"
ovmf-prebuilt = "0.2.4"

[build-dependencies]
llvm-tools = "0.1.1"
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }
bootloader = "0.11.13"
# bootloader = "0.11.12"
# bootloader = { path = "../../dev/git/bootloader"}

[workspace]
members = [ 
  "bootloader/common", "bootloader/proc_macros", 
  "bootloader/stage-0", 
  "bootloader/stage-1",
  "bootloader/stage-2",
  "bootloader/stage-3",
  "kernel"
  ]

[profile.dev]
panic = "abort"
opt-level = "s"
lto = true
codegen-units = 1
debug = false
overflow-checks = false
# inherits = "release"


[profile.release]
panic = "abort"
opt-level = "s"
lto = true
codegen-units = 1
debug = false
overflow-checks = false

